export const CAR_MAKES = [
  "Acura",
  "Audi",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "Mercedes-Benz",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
] as const;

export const CAR_MODELS: Record<string, string[]> = {
  Acura: ["ILX", "Integra", "MDX", "RDX", "TLX"],
  Audi: [
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q3",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "R8",
    "e-tron",
  ],
  BMW: [
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "7 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i4",
    "iX",
  ],
  Buick: ["Enclave", "Encore", "Encore GX", "Envision"],
  Cadillac: ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6"],
  Chevrolet: [
    "Blazer",
    "Camaro",
    "Corvette",
    "Equinox",
    "Malibu",
    "Silverado",
    "Suburban",
    "Tahoe",
    "Traverse",
    "Trailblazer",
    "Trax",
  ],
  Chrysler: ["300", "Pacifica", "Voyager"],
  Dodge: ["Challenger", "Charger", "Durango", "Hornet"],
  Ford: [
    "Bronco",
    "Bronco Sport",
    "Edge",
    "Escape",
    "Expedition",
    "Explorer",
    "F-150",
    "Focus",
    "Fusion",
    "Maverick",
    "Mustang",
    "Ranger",
    "Transit",
  ],
  GMC: ["Acadia", "Canyon", "Sierra", "Terrain", "Yukon"],
  Honda: [
    "Accord",
    "Civic",
    "CR-V",
    "Fit",
    "HR-V",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Ridgeline",
  ],
  Hyundai: [
    "Elantra",
    "Ioniq",
    "Ioniq 5",
    "Kona",
    "Palisade",
    "Santa Cruz",
    "Santa Fe",
    "Sonata",
    "Tucson",
    "Venue",
  ],
  Infiniti: ["Q50", "Q60", "QX50", "QX55", "QX60", "QX80"],
  Jaguar: ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF"],
  Jeep: [
    "Cherokee",
    "Compass",
    "Gladiator",
    "Grand Cherokee",
    "Renegade",
    "Wrangler",
  ],
  Kia: [
    "Carnival",
    "EV6",
    "Forte",
    "K5",
    "Niro",
    "Optima",
    "Rio",
    "Seltos",
    "Sorento",
    "Soul",
    "Sportage",
    "Telluride",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Lexus: [
    "ES",
    "GS",
    "GX",
    "IS",
    "LC",
    "LS",
    "LX",
    "NX",
    "RC",
    "RX",
    "RZ",
    "UX",
  ],
  Lincoln: ["Aviator", "Corsair", "Nautilus", "Navigator"],
  Maserati: ["Ghibli", "Levante", "Quattroporte"],
  Mazda: ["CX-30", "CX-5", "CX-50", "CX-90", "Mazda3", "Mazda6", "MX-5 Miata"],
  "Mercedes-Benz": [
    "A-Class",
    "C-Class",
    "CLA",
    "CLS",
    "E-Class",
    "EQB",
    "EQE",
    "EQS",
    "G-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "S-Class",
    "SL",
  ],
  Mitsubishi: ["Eclipse Cross", "Mirage", "Outlander", "Outlander Sport"],
  Nissan: [
    "Altima",
    "Armada",
    "Frontier",
    "Kicks",
    "Leaf",
    "Maxima",
    "Murano",
    "Pathfinder",
    "Rogue",
    "Sentra",
    "Titan",
    "Versa",
    "Z",
  ],
  Porsche: ["911", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Subaru: [
    "Ascent",
    "BRZ",
    "Crosstrek",
    "Forester",
    "Impreza",
    "Legacy",
    "Outback",
    "WRX",
  ],
  Tesla: ["Model 3", "Model S", "Model X", "Model Y"],
  Toyota: [
    "4Runner",
    "Avalon",
    "Camry",
    "Corolla",
    "Crown",
    "GR86",
    "Highlander",
    "Land Cruiser",
    "Prius",
    "RAV4",
    "Sequoia",
    "Sienna",
    "Tacoma",
    "Tundra",
    "Venza",
  ],
  Volkswagen: [
    "Arteon",
    "Atlas",
    "Atlas Cross Sport",
    "Golf",
    "ID.4",
    "Jetta",
    "Passat",
    "Tiguan",
    "Taos",
  ],
  Volvo: ["C40", "S60", "S90", "V60", "V90", "XC40", "XC60", "XC90"],
};

export const CAR_CLASSES = [
  "SUV",
  "Sedan",
  "Coupe",
  "Hatchback",
  "Wagon",
  "Pickup",
  "Minivan",
  "Convertible",
  "Crossover",
  "Luxury",
] as const;

export const FUEL_TYPES = [
  "Gas",
  "Diesel",
  "Electric",
  "Hybrid",
  "Plug-in Hybrid",
  "Flex-Fuel",
] as const;

export const DRIVE_TYPES = [
  { value: "fwd", label: "Front-Wheel Drive (FWD)" },
  { value: "rwd", label: "Rear-Wheel Drive (RWD)" },
  { value: "awd", label: "All-Wheel Drive (AWD)" },
  { value: "4wd", label: "Four-Wheel Drive (4WD)" },
] as const;

export const TRANSMISSION_TYPES = [
  { value: "a", label: "Automatic" },
  { value: "m", label: "Manual" },
] as const;

export const YEARS = Array.from({ length: 12 }, (_, i) => 2026 - i);
