export const mockCars = [
  // Original 10
  {
    city_mpg: 19,
    class: "compact car",
    combination_mpg: 21,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "toyota",
    model: "corolla",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 22,
    class: "compact car",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.8,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "toyota",
    model: "camry",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 20,
    class: "midsize car",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "bmw",
    model: "3 series",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "midsize car",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "bmw",
    model: "5 series",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 21,
    class: "suv",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "audi",
    model: "q5",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 16,
    class: "suv",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 22,
    make: "audi",
    model: "q7",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "honda",
    model: "civic",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 22,
    class: "midsize car",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "honda",
    model: "accord",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 17,
    class: "suv",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.6,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "jeep",
    model: "grand cherokee",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 15,
    class: "truck",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 5.7,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 22,
    make: "toyota",
    model: "tundra",
    transmission: "a",
    year: 2023,
  },

  // 30 NEW CARS
  {
    city_mpg: 24,
    class: "compact car",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "hyundai",
    model: "elantra",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 21,
    class: "midsize car",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "hyundai",
    model: "sonata",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "hyundai",
    model: "tucson",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "suv",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.8,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "kia",
    model: "telluride",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 35,
    make: "kia",
    model: "forte",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 19,
    class: "midsize car",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "kia",
    model: "k5",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 22,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "mazda",
    model: "cx-5",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "mazda",
    model: "cx-50",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 26,
    class: "compact car",
    combination_mpg: 30,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 36,
    make: "mazda",
    model: "mazda3",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 16,
    class: "truck",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.5,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 22,
    make: "ford",
    model: "f-150",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 21,
    class: "suv",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "ford",
    model: "escape",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "suv",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 2.7,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "ford",
    model: "explorer",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 15,
    class: "truck",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 6.2,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 20,
    make: "chevrolet",
    model: "silverado",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 22,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 1.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 31,
    make: "chevrolet",
    model: "equinox",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 19,
    class: "midsize car",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "chevrolet",
    model: "malibu",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 17,
    class: "suv",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.6,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "gmc",
    model: "acadia",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 14,
    class: "truck",
    combination_mpg: 16,
    cylinders: 8,
    displacement: 5.3,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 19,
    make: "gmc",
    model: "sierra",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "volkswagen",
    model: "jetta",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "volkswagen",
    model: "tiguan",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 21,
    class: "midsize car",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "volkswagen",
    model: "passat",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 19,
    class: "suv",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "subaru",
    model: "outback",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "subaru",
    model: "forester",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 24,
    class: "compact car",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 33,
    make: "subaru",
    model: "impreza",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 16,
    class: "suv",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 23,
    make: "lexus",
    model: "rx",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 22,
    class: "midsize car",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.5,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "lexus",
    model: "es",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "suv",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "acura",
    model: "mdx",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 21,
    class: "midsize car",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 29,
    make: "acura",
    model: "tlx",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "nissan",
    model: "rogue",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 23,
    class: "compact car",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "nissan",
    model: "sentra",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 15,
    class: "truck",
    combination_mpg: 17,
    cylinders: 6,
    displacement: 3.5,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 21,
    make: "nissan",
    model: "frontier",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 19,
    class: "suv",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.5,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 26,
    make: "mitsubishi",
    model: "outlander",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 17,
    class: "suv",
    combination_mpg: 20,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 24,
    make: "land rover",
    model: "defender",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 14,
    class: "suv",
    combination_mpg: 16,
    cylinders: 8,
    displacement: 4.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 19,
    make: "land rover",
    model: "range rover",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 18,
    class: "midsize car",
    combination_mpg: 21,
    cylinders: 4,
    displacement: 2.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 25,
    make: "mercedes-benz",
    model: "c-class",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 16,
    class: "midsize car",
    combination_mpg: 19,
    cylinders: 6,
    displacement: 3.0,
    drive: "rwd",
    fuel_type: "gas",
    highway_mpg: 23,
    make: "mercedes-benz",
    model: "e-class",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 20,
    class: "suv",
    combination_mpg: 23,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 27,
    make: "volvo",
    model: "xc60",
    transmission: "a",
    year: 2023,
  },
  {
    city_mpg: 22,
    class: "suv",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "volvo",
    model: "xc40",
    transmission: "a",
    year: 2022,
  },
  {
    city_mpg: 19,
    class: "midsize car",
    combination_mpg: 22,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "volvo",
    model: "s60",
    transmission: "a",
    year: 2023,
  },
];
